### ISSUE TITLE
Missing logger implementation

### ISSUE THREAD

**Issue by imdaveho** [scala/scala3.g8#157]
When getting started following the guide on the official Scala website, the instructions point to running `sbt new scala/scala3.g8` to get a hello world template up and running. However, you get this warning/error which isn't the greatest experience for a new comer:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Is there some way to specify version >= 2 in the template's build.sbt file? Otherwise this error will continue to pop up and you'd imagine that for a hello world representation, 0 errors should pop up especially the officially sanctioned instructions straight from the site.

**Comment by adpi2** [comment]
Thanks for the report.

> Is there some way to specify version >= 2 in the template's build.sbt file?

I am not sure what you mean by that.

However the errors should disappear after: https://github.com/foundweekends/giter8/pull/935

**Comment by SethTisue** [comment]
> > Is there some way to specify version >= 2 in the template's build.sbt file?

> I am not sure what you mean by that.

Probably a reference to slf4j 2.x — but no, we can't override that from here. But I guess it's moot since https://github.com/foundweekends/giter8/pull/935 took care of it.
